### ISSUE TITLE
Display test coverage

### ISSUE THREAD

**Issue by Leko** [phenyl-js/phenyl#104]
We need to know test coverage in all packages.
I think the best tool is [istanbuljs/nyc](https://github.com/istanbuljs/nyc).

**Comment by Leko** [comment]
@nd-02110114 ping

**Comment by nd-02110114** [comment]
@leko 
I introduced nyc to this repo by #106 

Now, there is not so much test code (.... maybe not so good thing....), 
i think we should change kocha (present test framework) to mocha if we have some plan about changing kocha for the future.

This change is not so hard.

Especially, before i start #105 
So, I want to start changing kocha to mocha. How about?
