### ISSUE TITLE
Add README for every module

### ISSUE THREAD

**Issue by shinout** [phenyl-js/phenyl#15]
- [ ] is-restorable
- [ ] mongolike-operations
- [ ] oad-utils
- [ ] phenyl-async-storage-client
- [ ] phenyl-core
- [ ] phenyl-dynamodb-client
- [ ] phenyl-http-client
- [ ] phenyl-http-rules
- [ ] phenyl-http-server
- [ ] phenyl-interfaces
- [ ] phenyl-lambda-adapter
- [ ] phenyl-memory-client
- [ ] phenyl-mongodb-client
- [ ] phenyl-redux
- [ ] phenyl-standards
- [ ] phenyl-state
- [ ] phenyl-utils
- [ ] power-assign
- [ ] power-crypt
- [ ] power-debugger
- [ ] power-filter

**Comment by sasurau4** [comment]
The good examples are better
