### ISSUE TITLE
Typescript Progress

### ISSUE THREAD

**Issue by Naturalclar** [phenyl-js/phenyl#164]
## Progress in typescript conversion

🏃- **In Progress**
:eyes: - **Needs Review**
✅ - **Done**
 
- [x] api-explorer (@imoans) :eyes:
- [x] api-explorer-client (@nicholaslee119)
- [x] ~~async-storage-client~~ (@nicholaslee119) [empty] 
- [x] central-state(@nicholaslee119) 
- [x] ~~dynamodb-client~~ (@nicholaslee119) [empty]
- [x] express (@Naturalclar)
- [x] http-client (@imoans) 
- [x] http-server (@imoans)
- [x] http-rules (@shinout)
- [x] interfaces (@shinout)
- [x] lambda-adapter (@Naturalclar) 
- [x] memory-db (@imoans)
- [x] mongo-db (@nicholaslee119)  
- [x] redux (@sasurau4 r)
- [x] rest-api (@shinout)
- [x] standards (@nicholaslee119) 
- [x] state (@imoans) 
- [x] utils (@shinout)
- [x] websocket-client (@imoans)
- [x] websocket-server (@imoans)

### 1. Checkout `typescript` branch

- All the works for converting to typescript are done on `typescript` branch.
- First, check out the branch

```
git checkout typescript
``` 

### 2. Choose a package to work on.

- Packages that are yet to be converted to typescripts are included in the `flow-modules` directory.
Chose a package that you'd like to work on.

**Check the `package.json` for its dependencies! You'll want to work on a package that does not depend on another package that has not been converted to typescript.**

- Create a new branch based from `typescript` branch

```
git chekcout -b feature/phenyl-bar-typescript
```

### 3. Move the package you chose from `flow-modules` to `modules` 

- use `git mv` to move the package from `flow-modules` to `modules`. This is to make sure that changes can be properly tracked  for reviewers to see the diff.

###  4. Delete the `phenyl-` prefix.

- Delete the `phenyl-` prefix from the package. For example, change `phenyl-interfaces` to `interfaces`

### 5. Add `tsconfig.json`. 

- Add `tsconfig.json` to the moved package.
- You can copy the [tsconfig.js in `phenyl-interfaces` ](https://github.com/phenyl-js/phenyl/blob/typescript/modules/interfaces/tsconfig.json). 

### 5. Modify `package.json`.

- Change the format of `package.json` so it looks like the [package.json in `phenyl-interfaces` ](https://github.com/phenyl-js/phenyl/blob/typescript/modules/interfaces/package.json). 
- In the `author` section of `package.json`, add your name and email.

### 6. Start converting to typescript!

- Convert the files in `src` file to typescript.

**Make sure to use `git mv` command to rename files from `.js` to `.ts`!!!!!
Changes won't be tracked if you rename the files directly on the editor.**

### 7. Send a PR!

- Make a new PR to `typescript` branch.

**Comment by imoans** [comment]
I'd like to work on `phenyl-websocket-client` and `phenyl-websocket-server`

**Comment by Naturalclar** [comment]
I'll work on `phenyl-lamba-adapter`

**Comment by imoans** [comment]
I'll work on `memory-db`

**Comment by Naturalclar** [comment]
I'll work on phenyl-redux

**Comment by nicholaslee119** [comment]
I will work on api-explorer-client

**Comment by nicholaslee119** [comment]
`dynamodb-client`  and `async-storage-client` are unimplemented, this is necessary to move them to `modules`?

**Comment by Naturalclar** [comment]
Thank you! Closing this issue since all the main files has been converted to typescript.
