### ISSUE TITLE
[oad-utils] Add more tests

### ISSUE THREAD

**Issue by shinout** [phenyl-js/phenyl#19]
- [ ] `sortByNotation`
- [ ] `getNestedValues`
- [ ] `normalizeQueryCondition`
- [ ] `normalizeUpdateOperation`
- [ ] `mergeUpdateOperations`
- [ ] `visitFindOperation`

**Comment by sasurau4** [comment]
oad-utils are renamed to https://github.com/phenyl-js/sp2
