### ISSUE TITLE
MongoDB conflict issue discussion

### ISSUE THREAD

**Issue by Naturalclar** [phenyl-js/phenyl#226]
## Overview 
Discuss a way to ensure that conflict of $push and $set does not prevent phenyl from committing to mongoDB

## Background
When commits are stored to unreachedCommits, there may be a case where a set of operation will cause a conflict when pushing them to mongoDB.

For example, when trying to push the following operations:

```
[
  {
    "$set": {
      "foo": {
        "bar": [{"value": "1"}]
       }
     }
  },
  {
    "$push": {
      "foo.bar": {"value": "2"}
     }
  },   
]
```

It will result in the following error on MongoDB side: 
`Updating the path .... would create a conflict at ...`

**Comment by shinout** [comment]
https://github.com/mongodb/mongo/blob/master/src/mongo/db/update/update_object_node.cpp

This implementation will also be the spec.

**Comment by shinout** [comment]
Tests
* https://github.com/mongodb/mongo/blob/master/src/mongo/db/update/update_object_node_test.cpp
* https://github.com/mongodb/mongo/blob/master/jstests/core/update_arrayFilters.js

**Comment by shinout** [comment]
We should detect all the cases that throw `ErrorCodes::ConflictingUpdateOperators`.

**Comment by sasurau4** [comment]
We have two approach to fix this issue.

1. Always commit operations without merging any operations when using push. 
2. If using push and not conflict operations, doesn't merge and commit operations.

Initially, we try to adapt 2.
