### ISSUE TITLE
Roadmap to v1

### ISSUE THREAD

**Issue by sasurau4** [phenyl-js/phenyl#239]
This is meta issue of roadmap to v1

- [x] #237 
- [x] #226 
- [x] add README
- [x] releasing from ci

If you have any other issues to for v1, please comment.

**Comment by shinout** [comment]
@Naturalclar @sasurau4 
Although the current README should be improved, I'd like to update this library to v1.
Can I try it from now?

**Comment by sasurau4** [comment]
@shinout OK, go ahead!

**Comment by shinout** [comment]
done!
