### ISSUE TITLE
jsnext.js should not use wildcard export for tree shaking.

### ISSUE THREAD

**Issue by shinout** [phenyl-js/phenyl#35]
It seems jsnext.js exports all the named values from index.js.
```js
export * from './src/index.js'
```
This may let bundlers read non-necessary values while some bundlers implement tree shaking.

- make jsnext.js a symbolic link to src/index.js
- write down all the values in jsnext.js
- copies src/index.js

Any ideas?

**Comment by sasurau4** [comment]
jsnext.js is removed by migration to TS
