### ISSUE TITLE
Improve merge-update-operations

### ISSUE THREAD

**Issue by fitzr** [phenyl-js/phenyl#43]
Improve [the following todo](https://github.com/phenyl-js/phenyl/blob/master/modules/oad-utils/src/merge-update-operations.js#L10)

```js
/**
 * Merge update operations.
 * TODO: Currently there are some cases are not merged well (See test cases.)
 */
export function mergeUpdateOperations(...operationList: Array<Object>): RegularUpdateOperation {
  return deepMerge.all(operationList.map(normalizeUpdateOperation))
}
```

**Comment by fitzr** [comment]
use [visitFindOperation](https://github.com/phenyl-js/phenyl/blob/master/modules/oad-utils/src/visit-find-operation.js#L21)

**Comment by sasurau4** [comment]
oad-utils are renamed to https://github.com/phenyl-js/sp2
