### ISSUE TITLE
How to fetch all entities?

### ISSUE THREAD

**Issue by fitzr** [phenyl-js/phenyl#70]
Is it impossible to fetch all entities?
As EntityClient.find() requires WhereQuery, it cannot use to find all.

**Comment by shinout** [comment]
You mean syntax sugar of `entityClient.find({ where: {} })`?

**Comment by fitzr** [comment]
I just wanna know how to do it.
Why is not the following allowed?
```js
entityClient.find({ entityName: 'user' })
entityClient.find({ entityName: 'user', where: null })
```

**Comment by sasurau4** [comment]
The workaround is querying by not existed condition

```
entityClient.find({ entityName: 'user', where: { 'id': { $ne: 'hoge'}} })
```
