### ISSUE TITLE
Support MongoDB 3.6 (mongodb@3.x）

### ISSUE THREAD

**Issue by Leko** [phenyl-js/phenyl#98]
Hi there.
MongoDB 3.6 has been released.

Release note:

> &mdash; [Release Notes for MongoDB 3.6 — MongoDB Manual 3.6](https://docs.mongodb.com/manual/release-notes/3.6/)

In Japanese:

> &mdash; [MongoDB 3.6 Release Notes 翻訳 - Qiita](https://qiita.com/kabao/items/ac14c779ea8ea110276f)

And now, [mongodb@3.0.0](https://github.com/mongodb/node-mongodb-native) supports MongoDB 3.6.
But it has some breaking changes between 2 to 3.

> &mdash; [node-mongodb-native/CHANGES_3.0.0.md at 3.0.0 · mongodb/node-mongodb-native](https://github.com/mongodb/node-mongodb-native/blob/3.0.0/CHANGES_3.0.0.md)

Have you planned to upgrade mongodb@3?

**Comment by shinout** [comment]
Upgrade has been done! Supporting ChangeStream is the next issue.
